### ISSUE TITLE
Changing the heading of Blog Page

### ISSUE THREAD

**Issue by ashutoshmjain** [jarrekk/Jalpc#50]
Jack 
Hope you are doing well. 
I wanted to change the heading of Blog page from 'Latest Blog" to 'Latest Posts' . Could you please point me to right place to make this change. 

Also I responded to your email yesterday. Hope you got it. Let me know if any help needed.

Thanks again

**Comment by jarrekk** [comment]
Hi @ashutoshmjain 

Thanks very much for your kind reply! It's comprehensive and valuable for me, I will consider it carefully and ask my friends, if I have questions I will ask for your advise 😄

About changing heading of Blog page, source code is at **blog/blog.html** line 11, edit this line to `<h1>Latest Blog</h1>`, I think your advise is nice and I will consider it.

And about icon question you asked me previous, I missed another place at index page career section, icons are located at time line, you can edit them whatever you like at file **_data/careers.yml**, there is `icon` attribute at each item.

Free free to ask me if you have any questions, thanks!

**Comment by ashutoshmjain** [comment]
Thanks  .. it worked 

While we are on this topic  .. Here is one more suggestion 

When we click on the Blog menu button on main page  , it scrolls me down to blog section .. that has nothing but a link to blog page .. why don't we remove that section as it is unnecessary , and rather take the viewer directly to blog posts page ... 

If its a technical requirement to scroll down the blog section , then we should provide something useful there .. for example a description of blogs and a little clickable button for 'more'. Alternatively we can display last three posts here .. Just a thought .. nothing mandatory :-)

**Comment by jarrekk** [comment]
Thanks for your suggestion.

When I designed this theme, I made it as index page first, viewers could get information and links from index page, it's also website owner profile page, so I used sections and anchors to realize it, recently I optimized index page: reducing request times and compressing css/ js files, because it took long time get total data from index page.

I think your suggestion is very nice, viewers can go to posts page directly or see some latest posts' title and go to posts page by clicking title. Once I thought blog section was unnecessary and superfluous, but most viewers see posts from other websites or search engines, they can go to posts detail page directly from links, so I didn't make changes, anyway I will consider it. 

BTW, if you want to change it to any of both methods, I am glad to help you realize it, it will not take long time to do it:)

**Comment by ashutoshmjain** [comment]
Thanks @jarrekk 

I think removing the blog section altogether is a better idea. We can have the top link directly jump to blog page.  Please help with code if it's not too much work. Else we can live with it -:) 

Your new template looks very good. I guess I will migrate to it once I finish moving all my posts (from various sources ) to the blog. I think once I have the posts figured out , migration won't take much. The new site loads faster. The skills template is very innovative. Keep up the good work. 

Cheers

**Comment by jarrekk** [comment]
Hi @ashutoshmjain 

I created a pull request to your repo just now, please [check](https://github.com/ashutoshmjain/homepage/pull/2) it, hope this will help you; and I think this new theme will be easy to merge, I made some changes to let others easier to use:)

Thanks!

**Comment by ashutoshmjain** [comment]
Thanks Jack @jarrekk  
I will work on it tonight as I want to do it from command line. This is my first 'pull request merge' experience. Want to make sure I understand how it works :-)
Cheers

**Comment by jarrekk** [comment]
OK, this'll be convenient for you to update and review:)

**Comment by ashutoshmjain** [comment]
Thanks  .. It worked  .. looking great 

Cheers
