### ISSUE TITLE
CSS clarification

### ISSUE THREAD

**Issue by joeSaad** [jarrekk/Jalpc#82]
Could you please put some clarification on how to change in the CSS of the site? colors? 
change css, build and see it in the site, which ones to start with. 
also uglifyjs is depreciated.

**Comment by AhmetBas** [comment]
@joeSaad You can see the explanation of @jarrekk in an old issue. https://github.com/jarrekk/Jalpc/issues/75

You can change the color etc in the static/css/style-purify file. For example you can find the part you have to change with Chrome inspect.

**Comment by joeSaad** [comment]
I can change it chrome inspect and off course that works. I just wanted to see the changes when changing in the original files. style-purify doesn't reflect the changes since it is not picked up in the html head of the page.

**Comment by jarrekk** [comment]
I was trying to use original css/js files when we run jekyll server, but now I haven't a solution since **node_module** folder is not included into **_site** folder when we run `jekyll server --watch`. Please see [#64](https://github.com/jarrekk/Jalpc/issues/64), if you guys have solutions, feel free to give your ideas or commit a PR, thanks!

**Comment by jarrekk** [comment]
Duplicated with #64, closed.
